import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';
import supabase from '../utils/SupabaseCli';
import { useState } from 'react';
import { Router, useRouter } from 'next/router';
import { useUser } from '@supabase/auth-helpers-react';
import DeclarerActeN from '@/Components/DeclareActeN';
import DeclarerActeM from '@/Components/DeclareActeM';
import DeclarerActeD from '@/Components/DeclareActeN';

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [userId, setUserId] = useState('');

  useEffect(() => {
    const getuser = async () => {
      const { data, error } = await supabase.auth.getUser();
      if (error) throw error.hint;

      console.log(data);
      //router.push('/Dashboard');
    };
    getuser();
  }, []);
  const router = useRouter();

  const checkLogin2 = async () => {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: email,
      password: password,
    });
    console.log(data);
    if (error) {
      setError(error.message);
      setTimeout(() => {
        setError('');
      }, 3000);
    } else {
      console.log(data);
      if (data.session) {
        setUserId(data.user.id);
        router.push('/Dashboard');
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  bg-slate-900 w-screen min-h-screen">
        <h1 className="text-white text-center py-6 text-3xl ">Login Page</h1>

        <section className="max-w-[475px] rounded-md mt-16 p-4  bg-slate-500  h-fit mx-auto flex justify-center  flex-col gap-5 items-center">
          <h1 className="text-white font-semibold text-xl">
            Insert Credentials
          </h1>
          <h2 className="text-red-400">{error} </h2>

          <div className="w-full">
            <h3 className="text-white my-1">Email:</h3>
            <input
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="text"
              placeholder="Your Email"
              className="rounded-md w-full py-2 px-2 outline-none focus:border-b-purple-900 focus:border-b-2"
            />
          </div>
          <div className="w-full">
            <h3 className="text-white my-1">Password:</h3>
            <input
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              type="password"
              placeholder="Your password"
              className="rounded-md  px-2  w-full py-2 outline-none focus:border-b-purple-900 focus:border-b-2"
            />
          </div>
          <button
            onClick={checkLogin2}
            className="w-full py-2 my-3 bg-black text-white"
          >
            Login
          </button>
          <a className="text-white hover:underline" href="/SignUp">
            vous etes un officier sans compte ?{' '}
          </a>
        </section>
      </main>
    </>
  );
}
